import { http, router as coreRouter } from '@inertiajs/core'
import type { HttpRequestConfig, HttpResponse, Page } from '@inertiajs/core'
import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'

import Show from '@/pages/Admin/Settings/Show'
import { formPatch, router, setPageProps } from '../support/inertia'
import { interestArea, reasonsStatus } from '../support/props'

const props = {
  schedule: { daily_time: '06:00', weekly_time: '09:00' }, whitelist: [],
  alerts: { email: { configured: true, label: 'mail' }, webhook: { configured: false, label: '未配置' } },
  reasons: reasonsStatus(), interest_areas: [interestArea(), interestArea({ id: 'ia-2', name: '前端开发' })],
}
const settings = (data: Record<string, unknown>): Page => ({
  component: 'Admin/Settings/Show', url: '/admin/settings', version: null,
  clearHistory: false, encryptHistory: false, rescuedProps: [], rememberedState: {}, flash: {},
  props: { errors: {}, current_user: { email: 'one@example.com' }, flash: {}, ...data },
})
const pending: { config: HttpRequestConfig; resolve: (response: HttpResponse) => void }[] = []
let installed: Page
const originalClient = http.getClient()

beforeEach(async () => {
  pending.length = 0
  history.replaceState({}, '', '/admin/settings')
  vi.spyOn(window, 'scrollTo').mockImplementation(() => {})
  Object.defineProperty(window.performance, 'getEntriesByType', { configurable: true, value: () => [] })
  http.setClient({ request: (config) => new Promise((resolve) => pending.push({ config, resolve })) })
  let initialized = false
  coreRouter.init({
    initialPage: settings(props), resolveComponent: () => Promise.resolve({}),
    swapComponent: async ({ page }) => { installed = page; initialized = true },
  })
  await waitFor(() => expect(initialized).toBe(true))
  setPageProps(settings(props).props)
})

afterEach(() => {
  coreRouter.cancelAll()
  http.setClient(originalClient)
  sessionStorage.clear()
  formPatch.mockReset()
  router.post.mockReset()
  router.patch.mockReset()
  router.reload.mockReset()
  vi.restoreAllMocks()
})

// Model the Rails partial-props response contract using the headers generated by
// the real installed Inertia router. Response merging/callback order are real core.
function reply(index: number, page: Page) {
  const request = pending[index]
  const only = request.config.headers?.['X-Inertia-Partial-Data']
  const sameComponent = request.config.headers?.['X-Inertia-Partial-Component'] === page.component
  const data = typeof only === 'string' && sameComponent
    ? { ...page, props: Object.fromEntries(Object.entries(page.props).filter(([key]) => only.split(',').includes(key))) }
    : page
  request.resolve({ status: 200, headers: { 'x-inertia': 'true' }, data: JSON.stringify(data) })
}

it.each(['schedule', 'model', 'alert'] as const)('%s 的晚到响应不能恢复已删除画像或移除新增画像', async (kind) => {
  render(<Show {...props} />)
  formPatch.mockImplementation((url, options) => coreRouter.patch(url, {}, options))
  router.post.mockImplementation((url, data, options) => coreRouter.post(url, data, options))
  const label = kind === 'schedule' ? '保存调度' : kind === 'model' ? '保存模型设置' : '发送测试告警'
  await userEvent.click(screen.getByRole('button', { name: label }))
  await waitFor(() => expect(pending).toHaveLength(1))

  // Delete A and create C while the other request still holds its old A/B snapshot.
  const changed = [props.interest_areas[1], interestArea({ id: 'ia-3', name: 'Rust' })]
  act(() => coreRouter.reload({ only: ['interest_areas'] }))
  await waitFor(() => expect(pending).toHaveLength(2))
  await act(async () => reply(1, settings({ interest_areas: changed })))
  await waitFor(() => expect(installed.props.interest_areas).toEqual(changed))

  const finished = vi.fn()
  const remove = coreRouter.on('finish', finished)
  await act(async () => reply(0, settings(props)))
  await waitFor(() => expect(finished).toHaveBeenCalled())
  remove()
  expect(installed.props.interest_areas).toEqual(changed)
})

it('离开页面后被真实 Inertia 丢弃的异步校验响应不会清除原行草稿', async () => {
  const view = render(<Show {...props} />)
  router.patch.mockImplementation((url, data, options) => coreRouter.patch(url, data, options))
  const row = screen.getByText('AI / LLM').closest('tr')!
  await userEvent.click(within(row).getByRole('button', { name: '编辑' }))
  fireEvent.change(within(row).getByLabelText('名称'), { target: { value: 'duplicate draft' } })
  await userEvent.click(within(row).getByRole('button', { name: '保存' }))
  await waitFor(() => expect(pending).toHaveLength(1))
  expect(sessionStorage.length).toBe(1)

  act(() => coreRouter.get('/admin/users'))
  await waitFor(() => expect(pending).toHaveLength(2))
  await act(async () => reply(1, { ...settings({}), component: 'Admin/Users/Index', url: '/admin/users' }))
  await waitFor(() => expect(installed.component).toBe('Admin/Users/Index'))
  view.unmount()

  const finished = vi.fn()
  const remove = coreRouter.on('finish', finished)
  await act(async () => reply(0, settings({ errors: { name: '名称已存在' } })))
  await waitFor(() => expect(finished).toHaveBeenCalled())
  remove()
  // Core ignores that settings response after navigation, then calls onSuccess
  // with the current Users page. A mounted/ownership guard must preserve the draft.
  expect(installed.component).toBe('Admin/Users/Index')
  expect(sessionStorage.length).toBe(1)
  setPageProps(settings(props).props)
  render(<Show {...props} />)
  expect(screen.getByDisplayValue('duplicate draft')).toBeInTheDocument()
})
